### PR TITLE
feat: add filtering option

### PR DESCRIPTION
**Pull request by im-adithya**
This adds filtering option to entitlements file if enabled

### CODE REVIEW

**Comment by im-adithya** [comment]
@nikwebr please review and let me know if anything's to be changed, it would be of great help if we can get this in!

**Comment by nikwebr** [comment]
Looks great. Thank you for the pull request :)

**Comment by im-adithya** [comment]
@nikwebr is it possible for you to make a new release with this filtering capability? Would be appreciated, thanks!

**Comment by nikwebr** [comment]
Sure, I made a new release. Sorry for the delay.

**Comment by im-adithya** [comment]
Thanks a lot!

**Pull request merged**
